### ISSUE TITLE
how to control the speed？

### ISSUE THREAD

**Issue by yunxiaoshan** [andresmendes/Vehicle-Dynamics-Lateral#6]
It seems there isnot an example to explain how to control the speed, We try to use simulink to control a car in lateral and longitudinal direction. However, it seems a little difficult to use the model.

**Comment by andresmendes** [comment]
Check the [SkidPad 4DOF](http://andresmendes.github.io/Vehicle-Dynamics-Lateral/html/SkidPad4DOF.html) example for speed control using a [simple proportional controller](https://github.com/andresmendes/Vehicle-Dynamics-Lateral/blob/master/Examples/SkidPad4DOF/VelControl4DOF.m).
